

runs:
  - hu_ok
  - hu_ok_curl
  - mixed_ilc
  - mixed_ilc_curl
  - shear


hu_ok:
  pols: TT,TE,EB,EE,TB
  xlmaxs: 3000,5000,5000,5000,5000
  ylmaxs: 3000,5000,5000,5000,5000
  xlmins: 500,500,500,500,500
  ylmaxs: 500,500,500,500,500
  xlxcuts: 50,50,50,50,50
  ylxcuts: 50,50,50,50,50
  xlycuts: 50,50,50,50,50
  ylycuts: 50,50,50,50,50
  mc: hu_ok,hu_ok,hu_ok,hu_ok,hu_ok
  xfields: ilc_standard,ilc_standard,pol,pol,ilc_standard
  yfields: ilc_standard,pol,pol,pol,pol

hu_ok_curl:
  pols: TT,TE,EB,EE,TB
  xlmaxs: 3000,5000,5000,5000,5000
  ylmaxs: 3000,5000,5000,5000,5000
  xlmins: 500,500,500,500,500
  ylmaxs: 500,500,500,500,500
  xlxcuts: 50,50,50,50,50
  ylxcuts: 50,50,50,50,50
  xlycuts: 50,50,50,50,50
  ylycuts: 50,50,50,50,50
  mc: hu_ok_curl,hu_ok_curl,hu_ok_curl,hu_ok_curl,hu_ok_curl
  xfields: ilc_standard,ilc_standard,pol,pol,ilc_standard
  yfields: ilc_standard,pol,pol,pol,pol
  
mixed_ilc:
  pols: TT,TT,TE,EB,EE,TB
  xlmaxs: 3000,5000,5000,5000,5000
  ylmaxs: 3000,5000,5000,5000,5000
  xlmins: 500,500,500,500,500
  ylmaxs: 500,500,500,500,500
  xlxcuts: 50,50,50,50,50
  ylxcuts: 50,50,50,50,50
  xlycuts: 50,50,50,50,50
  ylycuts: 50,50,50,50,50
  mc: hdv,hdv,hu_ok,hu_ok,hu_ok,hu_ok
  xfields: ilc_no_tsz,ilc_standard,ilc_standard,pol,pol,ilc_standard
  yfields: ilc_standard,ilc_no_tsz,ilc_standard,pol,pol,ilc_standard

mixed_ilc_curl:
  pols: TT,TT,TE,ET,EB,EE,TB
  xlmaxs: 3000,5000,5000,5000,5000
  ylmaxs: 3000,5000,5000,5000,5000
  xlmins: 500,500,500,500,500
  ylmaxs: 500,500,500,500,500
  xlxcuts: 50,50,50,50,50
  ylxcuts: 50,50,50,50,50
  xlycuts: 50,50,50,50,50
  ylycuts: 50,50,50,50,50
  mc: hdv,hdv,hu_ok,hu_ok,hu_ok,hu_ok
  xfields: ilc_no_tsz,ilc_standard,ilc_standard,pol,pol,pol,ilc_standard
  yfields: ilc_standard,ilc_no_tsz,ilc_standard,ilc_standard,pol,pol,ilc_standard

shear:
  pols: TT,TE,EB,EE,TB
  xlmaxs: 3500,5000,5000,5000,5000
  ylmaxs: 3500,5000,5000,5000,5000
  xlmins: 500,500,500,500,500
  ylmaxs: 500,500,500,500,500
  xlxcuts: 50,50,50,50,50
  ylxcuts: 50,50,50,50,50
  xlycuts: 50,50,50,50,50
  ylycuts: 50,50,50,50,50
  mc: shear,hu_ok,hu_ok,hu_ok,hu_ok
  xfields: ilc_standard,ilc_standard,pol,pol,ilc_standard
  yfields: ilc_standard,pol,pol,pol,pol
